### ISSUE TITLE
"No system RNG was patched for method:" warning reguarding Vanilla Events Expanded

### ISSUE THREAD

**Issue by Feliphysics** [rwmt/Multiplayer-Compatibility#254]
MpCompat is throwing a warning when starting the game with Vanilla events expanded enabled.
For all I know the warning could be safely ignored, so if that's the case feel free to close this out.

https://gist.github.com/HugsLibRecordKeeper/084118df27ebac06bca3126b35bcd3ec (hugslib log)
[Player.log](https://github.com/rwmt/Multiplayer-Compatibility/files/10512997/Player.log)

**Comment by notfood** [comment]
Fixed already. https://github.com/rwmt/Multiplayer-Compatibility/commit/52668fe417b6b400802eb912b3cf3c0aeee207e4

**Comment by Feliphysics** [comment]
First of all thanks for the answer.
However, I just uninstalled the game, made sure both the game and workshop folder were gone, then reinstalled.
Even after that I still get the warning, am I doing something wrong or did I simply misunderstand your answer?
(this was all done after the latest mp compat patch that came out around 40 minutes ago)

**Comment by notfood** [comment]
Mm, I see, it's just a warning. They removed the RNG possibly. I'll remove it from that method then.
